//
//  MMGeneratorTests.swift
//  Card Validator
//
//  Created by Maciej Matuszewski on 29.07.2017.
//  Copyright © 2017 Maciej Matuszewski. All rights reserved.
//

import XCTest
import EarlGrey

@testable import Card_Validator

class MMGeneratorTests: XCTestCase {
    
    override func setUp() {
        super.setUp()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    
    func testMMGeneratorVisa(){
        let digits = MMGenerator.shared.generateCardNumberDigits(
            withRandomDigits: [1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4],
            cardProvider:MMGenerator.CardProvider.Visa
        )
        let cardNumber = MMGenerator.shared.generateCardNumber(from:digits)
        XCTAssert(cardNumber == "4234 1234 1234 1232", "Not valid visa number generated by MMGenerator")
    }
    
    func testMMGeneratorMasterCard(){
        let digits = MMGenerator.shared.generateCardNumberDigits(
            withRandomDigits: [1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4],
            cardProvider:MMGenerator.CardProvider.MasterCard,
            masterCardRandomDigit: 2
        )
        let cardNumber = MMGenerator.shared.generateCardNumber(from:digits)
        XCTAssert(cardNumber == "5334 1234 1234 1238", "Not valid MasterCard number generated by MMGenerator")
    }
    
    func testMMGeneratorDiscover(){
        let digits = MMGenerator.shared.generateCardNumberDigits(
            withRandomDigits: [1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4],
            cardProvider:MMGenerator.CardProvider.Discover
        )
        let cardNumber = MMGenerator.shared.generateCardNumber(from:digits)
        XCTAssert(cardNumber == "6011 1234 1234 1236", "Not valid Discover number generated by MMGenerator")
    }
    
    func testMMGeneratorValidToPattern(){
        let cardNumber: String = MMGenerator.shared.generateCardNumber()
        
        XCTAssert(cardNumber.isValid(withPattern: "^([0-9]{4}[ ]){3}[0-9]{4}"), "Not valid number with pattern generated by MMGenerator")
    }
}
